name: "Aisenke"
description: "Aisenke Electronic Technology Co.,Ltd. Webpages"

url: "http://aisenke.github.io/home"
#url: "aisenke-local.com/home"

paginate: 5

markdown: redcarpet
permalink: pretty
pygments: true
